services:

  postgres:
    image: postgres:16-alpine
    container_name: fieldops-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: fieldops
      POSTGRES_USER: fieldops
      POSTGRES_PASSWORD: fieldops-dev-password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U fieldops -d fieldops"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  api:
    build:
      context: ./application
      dockerfile: Dockerfile

    image: fieldops-api:v1.0.0
    container_name: fieldops-api

    restart: unless-stopped

    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: fieldops
      DATABASE_USERNAME: fieldops
      DATABASE_PASSWORD: fieldops-dev-password

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy


volumes:
  postgres_data: